Added SAI-Challenger setup.
PLVision/DASH pull request #2
Opened 2022-08-29 12:38 UTC by maksymhedeon

1. Added SAI-Challenger submodule.
2. Added SAI-Challenger basic test.
3. Changed Makefile to build/start/stop SAI-Challenger.

2022-08-30 13:17 UTC, plvisiondevs requested changes

2022-08-30 13:17 UTC, plvisiondevs commented on test/test-cases/challenger_basic_test/conftest.py
> +commondir = os.path.join(curdir, '../common')
"common" content should be installed in the docker using ```python setup.py install```

2022-08-30 13:17 UTC, plvisiondevs commented on dash-pipeline/Makefile
> +sai-challenger-build:sai-challenger-client-build sai-challenger-server-build
Please add a comment that the server build is a temporary staff and has to be removed in the final version.
Add this comment to all server-related commands.

2022-08-30 13:17 UTC, plvisiondevs commented on test/test-cases/challenger_basic_test/conftest.py
> +commondir = os.path.join(curdir, '../common')
If I'm not mistaken, this is by default

2022-08-31 07:15 UTC, merged

2022-08-31 10:31 UTC, elchupanebrej commented on dash-pipeline/Makefile
> +        -v $(SAI_CHALLENGER_PATH)/../test-cases/challenger_basic_test/:/sai-challenger/tests \
Please add volume with dash tests. Please pay attention that dash tests will be stored in Dash repository, so please move  config here from SAI-Challenger repository

2022-08-31 10:31 UTC, elchupanebrej commented on dash-pipeline/Makefile
> +	cd $(SAI_CHALLENGER_PATH) && ./exec.sh -i client pytest --setup=../setups/sai_dpu_client_server.json -v -k "test_dpu_basic"
Please provide rootdir for pytest call