Test outbound snappi
PLVision/DASH pull request #21
Opened 2022-09-21 09:11 UTC by maksymhedeon

2022-09-27 10:05 UTC, maksymhedeon commented
This PR is depends on [this](https://github.com/PLVision/SAI-Challenger.OCP/pull/14)

2022-09-28 14:03 UTC, anton7811 requested changes

2022-09-28 14:03 UTC, anton7811 commented on test/test-cases/test_vector_example/test_sai_vnet_outbound_simple.py
> +            'VNI': {
For a single value it's enough to set just a string:
```
'VNI': OUTBOUND_VNI
```

2022-09-28 14:03 UTC, anton7811 commented on test/test-cases/test_vector_example/test_sai_vnet_outbound_simple.py
> +                    'STAGE1': {
The same is here. This is a single value.

2022-09-28 14:03 UTC, anton7811 commented on test/test-cases/test_vector_example/test_sai_vnet_outbound_simple.py
> +def metrics_ok(api, cfg):
I would like to see such function in the traffic_utils.

2022-09-28 14:03 UTC, anton7811 commented on test/test-cases/test_vector_example/test_sai_vnet_outbound_simple.py
> +    req.port.column_names = [req.port.FRAMES_TX, req.port.FRAMES_RX]
Looks like you are getting port counters and not flow counters.

2022-09-28 14:03 UTC, anton7811 commented on test/test-cases/test_vector_example/test_sai_vnet_outbound_simple.py
> +def wait_for(func, timeout=10, interval=0.2):
Please check that it is not duplicate of snappi/sai_dataplane.py.wait_for

2022-09-28 14:46 UTC, anton7811 commented on test/test-cases/test_vector_example/test_sai_vnet_outbound_simple.py
> +        assert wait_for(lambda: metrics_ok(api, cfg)), "Metrics validation failed!"
metrics_ok(dataplane)

2022-09-28 14:48 UTC, anton7811 commented on test/test-cases/test_vector_example/test_sai_vnet_outbound_scale.py
> +NUMBER_OF_VIP = 3
Please move these variables inside the test config.

Refer to https://github.com/mgheorghe/cgyang/blob/main/saigen/dflt_params.py

2022-09-28 15:45 UTC, anton7811 commented on test/test-cases/test_vector_example/test_sai_vnet_outbound_simple.py
> +    def test_simple_vxlan_packet(self, dpu, dataplane):
Let's add mark: `@pytest.mark("snappi")`

So it will be used to filter out ptf incompatible tests.

2022-09-30 10:14 UTC, maksymhedeon commented on test/test-cases/test_vector_example/test_sai_vnet_outbound_simple.py
> +def metrics_ok(api, cfg):
This temporary function

2022-09-30 10:14 UTC, maksymhedeon commented on test/test-cases/test_vector_example/test_sai_vnet_outbound_simple.py
> +def wait_for(func, timeout=10, interval=0.2):
This temporary function

2022-10-11 13:28 UTC, anton7811 approved these changes

2022-10-11 13:41 UTC, merged